### ISSUE TITLE
can not find policylearning.git

### ISSUE THREAD

**Issue by batulu9** [real-to-sim-to-real/RialToPolicyLearning#3]
When cloning github.com:iaileveragingrealtosim/policylearning.git,we couldn't find it on github.What does it do? Where can we find this project now?Thank you for your reply.

**Comment by SakethTecholution** [comment]
Clone the main repository  https://github.com/real-to-sim-to-real/RialToPolicyLearning.git

**Comment by MarcelTorne** [comment]
@batulu9 apologies for the mistake in the README.md, as @SakethTecholution mentioned, you should clone this main repo: `git clone git@github.com:real-to-sim-to-real/RialToPolicyLearning.git`

I updated the README
